#========================================
# Unit test specific settings
#========================================
#----------------------------------------
# Spring settings
#----------------------------------------
spring:
  main:
    banner-mode: "off"
    
#----------------------------------------
# Camunda settings
#----------------------------------------
camunda:
  bpm:
    deployment:
      autoDeployEnabled: false
      processes:
        - name: process_name_1
          tenant: tenant_id_1
          bpmnResourcePattern: bpmnResourcePattern_1
          dmnResourcePattern: dmnResourcePattern_1
          formResourcePattern: formResourcePattern_1
        - name: process_name_2
          tenant: tenant_id_2
          bpmnResourcePattern: bpmnResourcePattern_2
          dmnResourcePattern: dmnResourcePattern_2
          formResourcePattern: formResourcePattern_2
#----------------------------------------
# Rpa settings
# folderId per municipalityId
#----------------------------------------
integration:
  rpa:
    folderIds:
        2281: 50
        2260: 60
#----------------------------------------
# Integration settings
#----------------------------------------
config:
  common:
    token-uri: token.url
    client-id: client.id
    client-secret: client.secret
  camunda:
    base-url: camunda.base.url
  casedata:
    base-url: casedata.base.url
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  templating:
    base-url: templating.base.url
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  messaging:
    base-url: messaging.base.url
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  citizen:
    base-url: citizen.base.url
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  businessrules:
    base-url: businessrules.base.url
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  rpa:
    base-url: rpa.base.url
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
    identity-server-url: https://rpa.base.url/identity
  partyassets:
    base-url: partyassets.base.url
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
