#========================================
# Integration test specific settings
#========================================
#----------------------------------------
# Spring settings
#----------------------------------------
spring:
  application:
    name: pw-parking-permit-it
  main:
    banner-mode: "off"
    
#----------------------------------------
# Integration settings
#----------------------------------------
config:
  camunda:
    base-url: http://localhost:${wiremock.server.port}/api-camunda/engine-rest
  common:
    token-uri: http://localhost:${wiremock.server.port}/api-gateway/token
    client-id: the-client-id
    client-secret: the-client-secret
  casedata:
    base-url: http://localhost:${wiremock.server.port}/api-casedata
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  templating:
    base-url: http://localhost:${wiremock.server.port}/api-templating
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  messaging:
    base-url: http://localhost:${wiremock.server.port}/api-messaging
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  citizen:
    base-url: http://localhost:${wiremock.server.port}/api-citizen
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  businessrules:
    base-url: http://localhost:${wiremock.server.port}/api-business-rules
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  rpa:
    base-url: http://localhost:${wiremock.server.port}/api-rpa
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
    folder-id: 50
  partyassets:
    base-url: http://localhost:${wiremock.server.port}/api-party-assets
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}

texts:
  simplified-service:
    delay-days: 0
    