#========================================
# Integration test specific settings
#========================================
#----------------------------------------
# Spring settings
#----------------------------------------
spring:
  application:
    name: pw-parking-permit-it
  main:
    banner-mode: "off"
#----------------------------------------
# Rpa settings
# folderId per municipalityId
#----------------------------------------
integration:
  rpa:
    folderIds:
      2281: 50
      2260: 60
#----------------------------------------
# Integration settings
#----------------------------------------
config:
  camunda:
    base-url: http://localhost:${wiremock.server.port}/api-camunda/engine-rest
  common:
    token-uri: http://localhost:${wiremock.server.port}/api-gateway/token
    client-id: the-client-id
    client-secret: the-client-secret
  casedata:
    base-url: http://localhost:${wiremock.server.port}/api-casedata
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  templating:
    base-url: http://localhost:${wiremock.server.port}/api-templating
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  messaging:
    base-url: http://localhost:${wiremock.server.port}/api-messaging
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  citizen:
    base-url: http://localhost:${wiremock.server.port}/api-citizen
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  businessrules:
    base-url: http://localhost:${wiremock.server.port}/api-business-rules
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  rpa:
    base-url: http://localhost:${wiremock.server.port}/api-rpa
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
    folder-id: 50
  partyassets:
    base-url: http://localhost:${wiremock.server.port}/api-party-assets
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  support-management:
    base-url: http://localhost:${wiremock.server.port}/api-support-management
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}

texts:
  simplified-services:
    2281:
      delay: "PT5S"
    2260:
      delay: "PT5S"
  commons:
    2260:
      sendDigitalMail: true
  approvals:
    2260:
      description: Personen är folkbokförd i Ånge kommun. Rekommenderat beslut är att godkänna ansökan.
      subject: Beslut från Ånge kommun
      htmlBody: <p><strong>Hej</strong></p><p>Du har f&aring;tt ett beslut fr&aring;n Ånge kommun.</p><p>Med v&auml;nlig h&auml;lsning<br /><strong>Ånge kommun</strong></p>